SHOW DATABASES;
USE EMP;

SELECT * FROM EMP;

-- WAQTD THE DIFFERENT JOBS IN PRESENT IN EMPLOYEES TABLE
SELECT  DISTINCT JOB FROM EMP;

-- WAQTD THE DIFFERENT SAL OF THE EMPLOYESS;
SELECT distinct SAL FROM EMP;

-- WAQTD THE DETAILS OF THE EMPLOYEES WHOSE NAME IS SMITH.
SELECT * FROM EMP WHERE ENAME = 'SMITH';

-- WAQTD THE ENAME AND SAL OF ALL EMPLOYEES EARNING MORE THAN 1000;
SELECT ENAME , SAL FROM EMP WHERE SAL > 1000;  

-- WAQTD THE DETAILS OF THE EMPLOYEES EARNING SAL MORE THAN 2000 AND WORKING AS MANAGER.
SELECT * FROM EMP WHERE SAL > 2000 AND JOB = 'MANAGER';

-- WAQTD THE ENAME AND SAL OF THE EMPLOYEES HIRED AFTER 81 AND BEFORE 87;
SELECT ENAME , SAL , HIREDATE FROM EMP WHERE HIREDATE > '1981-12-31' AND HIREDATE < '1987-01-01';

-- WAQTD THE ENAME AND DEPTNO OF THE EMPLOYEE IS WORKING AS A SALESMAN IN DEPT NO 30;
SELECT ENAME , DEPTNO FROM EMP WHERE JOB= 'SALESMAN' AND DEPTNO = 30; 

-- WAQTD THE DETAILS OF THE EMPLOYEES HIRED DURING THE YEAR 81;
SELECT * FROM EMP WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-12-31';

-- WAQTD THE DETAILS OF THE EMPLOYESS WORKING AS A SALESMAN OR MANAGER 
SELECT * FROM EMP WHERE JOB = 'SALESMAN' OR JOB='MANAGER';

-- WAQTD THE ENAME AND SAL OF THE EMPLOYEES AFTER 81 OR WORKING AS A PRESIDENT
SELECT ENAME ,SAL ,JOB , HIREDATE FROM EMP WHERE (HIREDATE > '1981-12-31') AND JOB = 'PRESIDENT';
 
 -- WAQTD THE DETAILS OF THE EMP WORKING IN DEPNO 10 AND 20;
 SELECT * FROM EMP WHERE DEPTNO IN (10 , 20 );
 
 -- WAQTD THE NAME OF THE EMPLOYEES NOT WORKING AS A SALEMAN;
 SELECT ENAME,JOB FROM EMP WHERE NOT JOB = 'SALESMAN';
 
 -- WAQTD THE DETAILS OF THE 
 
 
SELECT * FROM EMP








