SHOW DATABASES;
USE EMP;

SELECT * FROM EMP;


-- FUNCTION QUESTIONS CLASS


-- WAQTD NUMBER OF EMPLOYEES HAVING 'A' IN THEIR NAMES 
select count(*) from emp where ename like '%A%';
-- 11.⁠ ⁠WAQTD NUMBER OF EMPS AND TOTAL SALary needed to pay THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L'S IN THEIR NAMES
select count(*) , sum(sal) from emp where ename like '%LL%' ;
-- ⁠WAQTD NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEE TABLE
select count(distinct job) from emp;
--  ⁠WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'M' IN THEIR NAMES;
SELECT count(*) FROM EMP WHERE ENAME LIKE '%M%';
-- ⁠WAQTD NUMBER OF EMPLOYEES HAVING ATLEAST 2 L'S  IN THEIR NAMES;
SELECT count(*) FROM EMP WHERE ENAME LIKE '%L%L%';
-- ⁠WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPT 30;
SELECT SUM(SAL) FROM EMP WHERE JOB IN ('CLERK') AND  DEPTNO IN (30);

-- ⁠WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEE
SELECT COUNT(DISTINCT SAL) FROM EMP;

-- WAQTD NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DISTINCT JOB) FROM EMP;

-- WATQD AVG SALARY GIVEN TO THE CLERK
SELECT AVG(SAL) FROM EMP WHERE JOB = 'CLERK';
