show databases;
use emp;

select * from emp;

-- 1.WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT
-- EXCEPT PRESIDENT
select count(*) , deptno from emp where   job != 'PRESIDENT' Group by deptno;

-- 2. WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN
-- EACH JOB
Select sum(SAL),job FROM EMP group by job;
-- 3.WAQTD NUMBER OF EMPLOYEES WORKING AS MANAGER IN EACH
-- DEPARTMENT
Select count(*),deptno from emp where job='MANAGER' group by deptno;
-- 4. WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT
-- EXCLUDING THE EMPLOYEES OF DEPTNO 20
select Avg(SAL) AS 'salary' , deptno from emp where deptno != 20 group by deptno;

-- 5.WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH J0B
select count(*), job from emp where ename like '%A%' GROUP BY JOB;

-- 6.WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT 
SELECT count(*) , avg(SAL) , DEPTNO FROM EMP WHERE SAL > 2000 GROUP BY DEPTNO;

-- 7.WAQTD TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMAN IN EACH DEPT
SELECT  SUM(SAL), count(*) , DEPTNO FROM EMP WHERE (JOB = 'SALESMAN') GROUP BY DEPTNO;

-- 8.WAOTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB 
SELECT MAX(SAL) , count(*) , JOB FROM EMP GROUP BY JOB;

-- 9.WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT 
SELECT MIN(SAL) , DEPTNO FROM EMP GROUP BY DEPTNO;

-- 10.WAOTD NUMBER OF TIMES THE SALARIES HAVE BEEN REPEATED IN EMPLOYEE TABLE
SELECT count(*) , SAL FROM  EMP GROUP BY SAL;

-- 11.WAQTD NUMBER OF EMPLOYEES HIRED ON THE SAME DAY INTO THE SAME DEPARTMENT
SELECT count(*) , DEPTNO , HIREDATE FROM EMP GROUP BY DEPTNO , HIREDATE;

-- 12.WAOTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT 
SELECT count(*) , SAL , JOB FROM EMP GROUP BY SAL , JOB;

-- 13.WAQTD NUMBER OF EMPLOYEES HAVING THE SAME NAME IN THE SAME DEPARTMENT
SELECT count(*) , ENAME , JOB FROM EMP GROUP BY ENAME , JOB;

-- 14. WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT AND HAVING THE SAME NAME
SELECT count(*) , ENAME , DEPTNO FROM EMP GROUP BY ENAME , DEPTNO;

-- 15. WAOTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY IN THE SAME DEPARTMENT AND HIRED ON THE SAME DAY
SELECT count(*) , SAL , DEPTNO , HIREDATE FROM EMP GROUP BY SAL , DEPTNO , HIREDATE;









