-- WAQTD DETAILS OF EMPLOVEES WORKING IN DEPT 10 OR 30
SELECT * FROM EMP WHERE DEPTNO IN ( 10 , 30);
--  ⁠WAQTD NAMES OF EMPLOYEES HIRED DURING 1982
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE LIKE '1982%';

-- ⁠WAQD NAME AND SALARY GIVEN TO THE EMPLOYEES EARNING COMMISSION
SELECT ENAME , SAL FROM EMP WHERE COMM IS NOT NULL;

-- WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK IN DEPT 10 OR 30 HAVING CHARACTER 'A' IN THEIR NAMES.
SELECT * FROM EMP WHERE JOB IN ('CLERK') AND DEPTNO IN (10,30) AND ENAME LIKE '%A%';

-- WAQTO NAMES OF THE EMPLOYEES HAVING CHAR 'S' AS THEIR LAST CHARACTER.
SELECT ENAME FROM EMP WHERE ENAME LIKE '%S';

-- WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1982 BUT BEFORE 1987
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE BETWEEN '1981-01-01' AND '1986-31-12';

-- ⁠WAQTD DETAILS OF THE EMPLOYEES WORKING AS ANALYST AND EARNING 4 DIGIT SALARY
SELECT * FROM EMP WHERE JOB = 'ANALYST' AND SAL LIKE '____';

-- WAQTD NAMES OF THE EMPLOYEES HIRED IN THE FIRST MONTH .
SELECT ENAME , HIREDATE FROM EMP WHERE HIREDATE LIKE '_____12___';

-- WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN AND DOSENT EARN ANY COMISSION
SELECT * FROM EMP WHERE JOB = 'SALESNAM' AND COMM IS NULL;

-- WAQTD NAME AND SALARY GIVEN TO THE EMPLOYEES HIRED DURING 1981 INTO DEPT 10 OR 40
SELECT ENAME , SAL FROM EMP WHERE HIREDATE LIKE '1981%' AND DEPTNO IN ( 10 , 40);

--  ⁠WAQTD DETAILS OF EMPLOYEES HAVING ONE L's PRESENT IN THE NAMES AND WORKS AS MANAGER
SELECT * FROM EMP WHERE JOB ='MANAGER' AND ENAME LIKE '%L%';

-- ⁠ ⁠WAQTD NAMES OF EMPLOYEES WHO EARN COMMISSION BUT NOT SALARY
SELECT ENAME FROM EMP WHERE COMM IS NOT NULL AND SAL IS NULL;

-- WAQTD NAMES OF THE EMPLOYEES IF NAME STARTS WITH 'A' OR 'J'
SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' OR ENAME LIKE 'J%';

-- LIST ALL THE EMPLOYEE NAMES EXCEPT FOR THE EMPLOYEES WHO' NAME HAS 'A' AS THE 3rd CHARTER •
SELECT ENAME FROM EMP WHERE ENAME LIKE '___A%';

-- LIST THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER'S AND HIREQ AFTER 1984 AND HAS A NAME WHICH ENDS WITH 'S' 

 SELECT * FROM EMP WHERE JOB = 'MANAGER' AND HIREDATE > '1984-12-31' AND ENAME LIKE '%S';
 
 -- WAQTD THE DETAILS OF THE EMPLOYEES NOT EARNING COMM 
 SELECT * FROM EMP WHERE COMM IS NULL OR COMM = 0;
